= Markdown to AsciiDoc converter
:library-version: 2.0.0

image:https://github.com/markdown-asciidoc/markdown-to-asciidoc/actions/workflows/build.yml/badge.svg[Build Status]
image:https://github.com/markdown-asciidoc/markdown-to-asciidoc/actions/workflows/release.yml/badge.svg[Publish Status]

image:https://badges.gitter.im/Join%20Chat.svg[link="https://gitter.im/markdown-asciidoc/markdown-to-asciidoc?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]
image:https://maven-badges.herokuapp.com/maven-central/io.github.markdown-asciidoc/markdown-to-asciidoc/badge.svg?style={style}[link=https://maven-badges.herokuapp.com/maven-central/io.github.markdown-asciidoc/markdown-to-asciidoc]
image:https://img.shields.io/github/license/apache/maven.svg?label=License[link=LICENCE]

A small, lightweight converter for Markdown to http://www.asciidoc.org[AsciiDoc] written in Java, and based on https://github.com/sirthias/pegdown[Pegdown].

Uses https://github.com/markdown-asciidoc/markdown-to-asciidoc/tree/master/src/test/resources/nl/jworks/markdown_to_asciidoc[Cucumber tests] as a reusable
set to test conversion between Markdown and AsciiDoc.

== Features

Currently, the following are supported by the Markdown to AsciiDoc converter:

* Code blocks
* Definition lists
* Headings
* Lines
* Links
* Lists (ordered, unordered, nested, mixed)
* Basic markup (bold, italic, monospaced, etc)
* Tables (including alignments)

Also, currently known *not* supported items are:

* Table cell spanning

== Usage

Add the following dependency to your project:

`nl.jworks.markdown_to_asciidoc:markdown_to_asciidoc:{library-version}`

To use the library, call the following:

`assertEquals("= Title", Converter.convertMarkdownToAsciiDoc("# Title"));`

The Converter converts all Markdown input to AsciiDoc.

== Uses

Currently, the conversion library is used in the https://plugins.jetbrains.com/plugin/7391[IntelliJ AsciiDoc Plugin] to seamlessly convert Markdown to AsciiDoc.

If you know of any projects using the library, please let me know on Twitter: http://www.twitter.com/epragt[@epragt].

== Bugs

If you find a bug or a missing feature, please report it the https://github.com/markdown-asciidoc/markdown-to-asciidoc/issues[Github Issue Tracker].
