= Markdown to AsciiDoc converter

image:https://badges.gitter.im/Join%20Chat.svg[link="https://gitter.im/bodiam/markdown-to-asciidoc?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]

image:https://travis-ci.org/bodiam/markdown-to-asciidoc.svg["Build Status", link="https://travis-ci.org/bodiam/markdown-to-asciidoc"]

A small, lightweight converter for Markdown to http://www.asciidoc.org[AsciiDoc] written in Java, and based on http://pegdown.org[Pegdown].

Uses https://github.com/bodiam/markdown-to-asciidoc/tree/master/src/test/resources/com/laamella/markdown_to_asciidoc[Cucumber tests] as a reusable
set to test conversion between Markdown and AsciiDoc.

== Features

Currently, the following are supported by the Markdown to AsciiDoc converter:

* Code blocks
* Definition lists
* Headings
* Lines
* Links
* Lists (ordered, unordered, nested, mixed)
* Basic markup (bold, italic, monospaced, etc)
* Tables (including alignments)

Also, currently known *not* supported items are:

* Table cell spanning

== Uses

Currently the conversion library is used in the https://plugins.jetbrains.com/plugin/7391[IntelliJ AsciiDoc Plugin] to seamlessly convert between
from Markdown to AsciiDoc.

If you know of any projects using the library, please let us know on Twitter:
http://www.twitter.com/macumbamacaca[@macumbamacaca] or http://www.twitter.com/epragt[@epragt].

== Bugs

If you find a bug or a missing feature, please report it the https://github.com/bodiam/markdown-to-asciidoc/issues[Github Issue Tracker].
